### PR TITLE
53: Validate geo-json data to WGS84 coordinate system for Solr

### PR DESCRIPTION
**Pull request by thePanz**

### CODE REVIEW

**Review by pantierra — COMMENTED** [review]
WGS84 also [includes the value `-180`](http://spatialreference.org/ref/epsg/wgs-84/). As far as I see from your tests it would declare `false` when this value is given. It looks like SOLR accepts only `-179.99`, so it would be nice if the K-Search could handle this case. And to validate against also the edge cases of WGS84.

**Comment by thePanz** [comment]
@xamanu how should the KSearch handle this case? rewrite the value of `-180` to `-179.99`?

**Comment by pantierra** [comment]
Probably it would be good to do this and leave a note in the documentation. Do you think it would be good to open an issue on the Solr project?

**Comment by thePanz** [comment]
I'd rather like to not alter the user provided data. And add a note to the fields that the negative boundaries *must* not be used (for now) due to the search-engine limitation. WDYT?

FYI: a solr/lucene ticket has been created https://issues.apache.org/jira/browse/LUCENE-8522

**Comment by pantierra** [comment]
In my opinion the K-Search should stick to the standard WGS84. And I'd prefer that K-Search covers the bad function of SOLR, until it is fixed upstream.

**Comment by thePanz** [comment]
@xamanu Fixed, handling LUCENE-8522 before sending the query to Solr.

**Review by avvertix — APPROVED** [review]

**Pull request merged**
